blank_issues_enabled: false
contact_links:
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=agenticflowx.agenticflowx&ssr=false#review-details
      about: Enjoying AgenticFlowX? Leave a review here!
